services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: backend
    image: time-manager-backend:dev
    depends_on:
      - db
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "${BACKEND_PORT_EXTERNAL:-8081}:8080"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    image: time-manager-frontend:dev
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      BACKEND_URL: http://backend:8081
    ports:
      - "${FRONTEND_PORT_EXTERNAL:-8080}:8080"
    volumes:
      - ./frontend/time_manager:/app:delegated
      - flutter_pub_cache:/root/.pub-cache

volumes:
  postgres_data:
  flutter_pub_cache: