name: Release APK

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build & Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify tag is on main branch
        run: |
          if ! git branch -r --contains ${{ github.ref }} | grep -q 'origin/main'; then
            echo "Error: Tag must be on main branch"
            exit 1
          fi

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Building version: $VERSION"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.5'
          channel: 'stable'

      - name: Get dependencies
        run: |
          cd frontend/time_manager
          flutter pub get

      - name: Build APK
        run: |
          cd frontend/time_manager
          flutter build apk --release \
            --build-name=${{ steps.version.outputs.version }} \
            --build-number=${{ github.run_number }}

      - name: Rename APK
        run: |
          cd frontend/time_manager/build/app/outputs/flutter-apk
          mv app-release.apk time-manager-${{ steps.version.outputs.version }}.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: frontend/time_manager/build/app/outputs/flutter-apk/time-manager-${{ steps.version.outputs.version }}.apk
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
