name: Sync to Private Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to private repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@github.com:${{ secrets.ORGANIZATION_NAME }}/${{ secrets.PRIVATE_REPO_NAME }}.git
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}