name: Sync to Private Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Push to private repository
        run: |
          git remote add private https://x-access-token:${{ secrets.PRIVATE_REPO_TOKEN }}@github.com/${{ secrets.ORGANIZATION_NAME }}/${{ secrets.PRIVATE_REPO_NAME }}.git
          git push private main --force